# This file was generated by GoReleaser. DO NOT EDIT.
cask "tinyraven" do
  version "0.3.14"

  on_macos do
    on_intel do
      sha256 "0224298b265f9f9da81b0c97b6652ce071ac575ead83f452ca9a240f3019e66f"
      url "https://github.com/ravencloak-org/tiny/releases/download/v#{version}/tinyraven_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4a93cac550fa5914c21e9adb6cd37c95330bf3a7904a57079f3542b2fc390dd"
      url "https://github.com/ravencloak-org/tiny/releases/download/v#{version}/tinyraven_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "87c58a8a08f8c59beabd88fc64856a8c75eceb579be21943ed60ad419bd6e7c6"
      url "https://github.com/ravencloak-org/tiny/releases/download/v#{version}/tinyraven_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3925a8981abd2d1cfeb4f65fb5f16ea57f491f6a097c5d4cb12264c018731ecd"
      url "https://github.com/ravencloak-org/tiny/releases/download/v#{version}/tinyraven_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tinyraven"
  desc "Open-source, self-hosted, drop-in alternative to Tinybird (binary: tinyraven)"
  homepage "https://github.com/ravencloak-org/tiny"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tinyraven"

  generate_completions_from_executable "tinyraven", "completion",
    base_name: "tinyraven",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
