# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tinyraven < Formula
  desc "Open-source, self-hosted, drop-in alternative to Tinybird (binary: tinyraven)"
  homepage "https://github.com/ravencloak-org/tiny"
  version "0.3.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.11/tinyraven_0.3.11_darwin_amd64.tar.gz"
      sha256 "2b1ceb5ec9b18916aba08f39ba58f26afc5c3546735ef34ff9c5995a56146373"

      define_method(:install) do
        bin.install "tinyraven"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.11/tinyraven_0.3.11_darwin_arm64.tar.gz"
      sha256 "d6dc1c55e58584d116d85da58471bcf5c21a07ead06863c6c755d23d2b2c98eb"

      define_method(:install) do
        bin.install "tinyraven"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.11/tinyraven_0.3.11_linux_amd64.tar.gz"
      sha256 "24014c7829705da73a2dff9a9afab88f5e1ea5e3697f5e6a1f4df9b07b626c3d"
      define_method(:install) do
        bin.install "tinyraven"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.11/tinyraven_0.3.11_linux_arm64.tar.gz"
      sha256 "0bf12523c45222e134a075bfc4a6e4f1200ffd30144c42e9e016bcc2ec20eb95"
      define_method(:install) do
        bin.install "tinyraven"
      end
    end
  end

  test do
    system "#{bin}/tinyraven", "--version"
  end
end
