# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tinyraven < Formula
  desc "Open-source, self-hosted, drop-in alternative to Tinybird (binary: tr)"
  homepage "https://github.com/ravencloak-org/tiny"
  version "0.3.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.9/tinyraven_0.3.9_darwin_amd64.tar.gz"
      sha256 "fd551067c7908d27af967930126f3d528815546e5490879478c64972cf715692"

      define_method(:install) do
        bin.install "tr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.9/tinyraven_0.3.9_darwin_arm64.tar.gz"
      sha256 "5284597f61fcc442ea6159e6ed1a86fcd7c988bec51f555bc4283abc34d45de4"

      define_method(:install) do
        bin.install "tr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.9/tinyraven_0.3.9_linux_amd64.tar.gz"
      sha256 "4bd72b9b417d5124b6a19d5848f2d20ad20fdc1ea034247a90e642d3709d6540"
      define_method(:install) do
        bin.install "tr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ravencloak-org/tiny/releases/download/v0.3.9/tinyraven_0.3.9_linux_arm64.tar.gz"
      sha256 "fa27a733d293802792ab3eab98df8ebc4dd33f7787893a117e902038119619f7"
      define_method(:install) do
        bin.install "tr"
      end
    end
  end

  test do
    system "#{bin}/tr", "--version"
  end
end
